name: Release Images

on:
  workflow_dispatch: {}
  push:
    branches: [ mas-ad ]
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

publish-image:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Image Tag
        run: |
          set -x
          if [ -z "${{inputs.image-tag}}" ]
          then
            echo "image-tag=latest" >> $GITHUB_ENV
            echo "Setting Image tag as '${{env.image-tag}}'"
          else
            echo "image-tag=${{ inputs.image-tag }}" >> $GITHUB_ENV
            echo "Setting Image tag as '${{env.image-tag}}'"
          fi

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Login to Quay.io Registry
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/rishabprasad005/apicurio-studio-editors:${{ env.image-tag }}
            quay.io/rishabprasad005/apicurio-studio-editors:${{ env.image-tag }}